# Generated by Django 2.0 on 2018-08-17 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('company_address', models.CharField(max_length=40)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, unique=True)),
                ('customer_transport', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_location', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Company')),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_firstname', models.CharField(max_length=20)),
                ('employee_secondname', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_thirdname', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_privillage', models.IntegerField(default=1)),
                ('employee_position', models.CharField(max_length=20)),
                ('employee_address', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_sale_limit', models.FloatField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_item', models.CharField(default='expense', max_length=40)),
                ('expense_receiver', models.CharField(default='receiver', max_length=40)),
                ('expense_description', models.TextField(blank=True, null=True)),
                ('expense_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Account')),
                ('expense_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_price', models.FloatField(default=10000, null=True)),
                ('item_size', models.FloatField(blank=True, null=True)),
                ('item_color', models.CharField(blank=True, max_length=40, null=True)),
                ('item_manufucture', models.CharField(blank=True, max_length=50, null=True)),
                ('item_discount', models.FloatField(blank=True, null=True)),
                ('item_package_name', models.CharField(blank=True, default='single', max_length=20, null=True)),
                ('item_package_quantity', models.FloatField(blank=True, null=True)),
                ('item_per_package', models.FloatField(blank=True, null=True)),
                ('item_minimum_allowed_quantity', models.FloatField(blank=True, default=20, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminuser', models.IntegerField(blank=True, null=True)),
                ('issueuser', models.IntegerField(blank=True, null=True)),
                ('sales_quantity', models.FloatField()),
                ('sales_amount', models.FloatField()),
                ('sales_balance', models.FloatField(default=0)),
                ('sales_loan', models.BooleanField(default=True)),
                ('sales_method_payment', models.CharField(default='cash', max_length=10)),
                ('sales_received', models.BooleanField(default=False)),
                ('sales_authorized', models.BooleanField(default=False)),
                ('sales_issue_item', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40)),
                ('store_address', models.CharField(max_length=40)),
                ('store_phone', models.CharField(max_length=20)),
                ('store_email', models.EmailField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Company')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='account_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Company'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
