# Generated by Django 2.0 on 2018-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_received',
            field=models.BooleanField(default=False),
        ),
    ]
