# Generated by Django 2.0 on 2018-06-29 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_sales_sales_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Company')),
                ('account_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_description', models.CharField(max_length=40)),
                ('expense_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Account')),
                ('expense_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_transport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_privillage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='item_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_package_name',
            field=models.CharField(blank=True, default='single', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_package_quantity',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_per_package',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='adminuser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='issueuser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_issue_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_method_payment',
            field=models.CharField(default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
