# Generated by Django 2.0 on 2018-07-02 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180629_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Company'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_package_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
